# escape=`
FROM mongo:xenial
MAINTAINER denisermolovich@gmail.com
#ToDo: Move env params to outside
ENV MONGO_INITDB_ROOT_USERNAME=root`
    MONGO_INITDB_ROOT_PASSWORD=0i&QpDhV&p*O`
    MONGO_INITDB_DATABASE=auth
COPY initDbScript.js /docker-entrypoint-initdb.d/
